### PR TITLE
Specify contact-point-discovery.port-name

### LINKED ISSUE #177: reactive-cli not working with reactive-lib 1.5.0
The yml file generated by reactive-cli will configure the akka management http to use port name "akka-mngt-http", but Cluster Bootstrap in reactive-lib will do lookup using port name "management". As a consequence, the cluster bootstrap will never find other nodes. 

This was probably introduced when we updated the akka-management version in reactive-lib (done by your truly).

### PR DESCRIPTION
**Pull request by eed3si9n**
This is on top of https://github.com/lightbend/reactive-cli/pull/184

Fixes #177

This specifies the management endpoint name explicity to `-Dakka.management.cluster.bootstrap.contact-point-discovery.port-name`.
By default the management endpoint name will fallback to `"akka-mgmt-http"` for backward compatibility.

In the future, sbt-reactive-app can declare the management endpoint name using "management-endpoint" as a label on the Docker image. See lightbend/sbt-reactive-app#164.

These changes combined together provides softlanding of the switch to `"management"` in akka/akka-management#274.

/cc @lightbend/play-lagom

### CODE REVIEW

File: cli/shared/src/main/scala/com/lightbend/rp/reactivecli/annotations/Annotations.scala [hunk 1]
```diff
@@ -36,6 +36,8 @@ case class Annotations(
   memory: Option[Long],
   cpu: Option[Double],
   endpoints: Map[String, Endpoint],
+  remotingEndpointName: Option[String],
```
Comment (renatocaval) [inline cli/shared/src/main/scala/com/lightbend/rp/reactivecli/annotations/Annotations.scala]: Is this being used? I did a quick search and it seems that this field is never read.

Comment (eed3si9n) [reply cli/shared/src/main/scala/com/lightbend/rp/reactivecli/annotations/Annotations.scala]: I can remove that one probably.
